nginx:
  image: chhewangsrp/portfolio-nginx
  tag: latest
  name: nginx
  ports:
    - 80
    - 443
  configMountPath: /etc/nginx/conf.d/default.conf
  certsMountPath: /etc/ssl/certs

api:
  image: chhewangsrp/portfolio-prod-api
  tag: latest
  name: api
  port: 8000
  env:
    - name: USER
      value: chhew
    - name: UID
      value: "197618"
    - name: USER_EMAIL
      value: chhewangsrp@gmail.com
    - name: COMPOSE_PROJECT_NAME
      value: portfolio
    - name: PORT_API
      value: "8000"
    - name: PORT_WEB
      value: "3000"
    - name: HOST_NAME
      value: localhost
    - name: RUN_SETUP_DJANGO
      value: "true"
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_DB
      value: portfolio
    - name: POSTGRES_PASSWORD
      value: MyGreatPassword!
    - name: SECRET_KEY
      value: my_key

  volumeMountPath: /portfolio

web:
  image: chhewangsrp/portfolio-prod-web
  tag: latest
  name: web
  ports:
    - 3000
  env:
    - name: NODE_ENV
      value: development
    - name: NEXT_TELEMETRY_DISABLED
      value: "1"
  volumeMountPath: /portfolio

database:
  image: chhewangsrp/portfolio-prod-database
  tag: latest
  name: database
  ports:
    - 5432
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_DB
      value: portfolio
    - name: POSTGRES_PASSWORD
      value: MyGreatPassword!
