stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - reset

variables:
  HOST_NAME: $HOST_NAME
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  PORT_WEB: $PORT_WEB
  SECRET_KEY: $SECRET_KEY

# Set environment variable and run
build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo '
      HOST_NAME=${HOST_NAME}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      PORT_WEB=${PORT_WEB}
      SECRET_KEY=${SECRET_KEY}
      ' > .env
    - docker-compose up --build -d
    - echo "build complete."

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."
    - docker-compose exec api logs

reset-test-job:
  stage: reset
  script:
    - echo "Taking down containers"
    - docker-compose down
    - echo "reset complete"
