version: '3.7'

services:
  # Postgres
  database:
    image: portfolio/postgres-${USER}
    build: ./db/
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432

  # Spring Boot API development server
  api:
    image: portfolio/api-${USER}
    build:
      context: ./api/
      args:
        USER: ${USER}
        UID: ${UID}
    restart: unless-stopped
    command: ["java", "-jar", "/portfolio/your-spring-app.jar"]
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_LOGGING_LEVEL_ROOT: INFO
      SPRING_SERVER_PORT: 5000
    ports:
      - ${PORT_API}:8080
    volumes:
      # Mount local dev files into container
      - ./api/src:/portfolio/

  # Node-based Next.js Webapp Development Server
  web:
    image: portfolio/web-${USER}
    build: ./web/
    restart: unless-stopped
    command: npm run dev
    depends_on:
      - api
      - database
    environment:
      - ENV
    volumes:
      - ./web/:/portfolio/
    ports:
      - ${PORT_WEB}:3000
