version: '3.7'

services:
  nginx:
    image: chhewangsrp/portfolio-nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
    - "80:80"
    - "443:443"
  # Postgres
  database:
    image: chhewangsrp/portfolio-database
    build: ./db/
    restart: unless-stopped
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: postgres
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432

  # Django API development server
  api:
    image: chhewangsrp/portfolio-api
    build:
      dockerfile: Dockerfile
      context: ./api/
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./api/src:/portfolio
    ports:
      - "8080:8080"

  # Node-based Next.js Webapp Development Server
  web:
    image: chhewangsrp/portfolio-web
    build:
      dockerfile: Dockerfile
      context: ./web/
    restart: unless-stopped
    command: npm run dev
    depends_on:
      - api
      - database
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./web/:/portfolio/
