version: '3.7'

services:
  nginx:
    build:
      dockerfile: Dockerfile.production
      context: ./nginx
    restart: always
    ports:
    - "80:80"
  # Postgres
  database:
    image: portfoliocontainerreg.azurecr.io/postgres
    build: ./db/
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: django_portfolio
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432
  # Django API development server
  api:
    image: portfoliocontainerreg.azurecr.io/api
    build:
      dockerfile: Dockerfile.production
      context: ./api/
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - database
    env_file:
      - .env 
  # Node-based Next.js Webapp Development Server
  web:
    image: portfoliocontainerreg.azurecr.io/web
    build:
      dockerfile: Dockerfile.production
      context: ./web/
    restart: unless-stopped
    command: npm run dev
    depends_on:
      - api
      - database
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    