version: '3.7'

services:
  # Postgres
  database:
    image: portfoliocontainerreg.azurecr.io/postgres
    build: ./db/
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: django_portfolio
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432

  # Django API development server
  api:
    image: portfoliocontainerreg.azurecr.io/api
    build:
      context: ./api/
      args:
        USER: ${USER}
        UID: ${UID}
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - database
    environment:
      - RUN_SETUP_DJANGO=true
      - DEBUG=true
      - HOST_NAME
      - PORT_WEB
      - PORT_API
    ports:
      - ${PORT_API}:8080
    volumes:
      # Mount local dev files into container
      - ./api/src:/portfolio/

  # Node-based Next.js Webapp Development Server
  web:
    image: portfoliocontainerreg.azurecr.io/web
    build: ./web/
    restart: unless-stopped
    command: npm run dev
    depends_on:
      - api
      - database
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./web/:/portfolio/
    ports:
      - ${PORT_WEB}:3000
      - 49153:49153
