apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.nginx.name }}
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
          ports:
            - containerPort: 80
            - containerPort: 443