apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: {{ .Values.database.name }}
  selector:
    app: {{ .Values.database.name }}
