apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      containers:
        - name: {{ .Values.web.name }}
          image: "{{ .Values.web.image }}:{{ .Values.web.tag }}"
          ports:
            - containerPort: 3000
          env:
            {{- toYaml .Values.web.env | nindent 12 }}