apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          imagePullPolicy: Never
          image: chhewangsrp/portfolio-prod-web
          ports:
            - containerPort: 3000
