apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: TXlHcmVhdFBhc3N3b3JkIQ==
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLS0rNmxsYXk1eGhmcjklNXIwdW82OStieTZhMyUqbWtfMkAoKSlmKi0ldHIleGhyK2hj
