FROM node:19.0 AS builder

ARG APPDIR=/portfolio/
WORKDIR ${APPDIR}

ADD . ${APPDIR}
RUN npm ci && \
    npm run build

# FROM nginx:1.21-alpine
# COPY --from=builder /portfolio/build /var/www

# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/conf.d